# Template: https://github.com/teppeis-sandbox/circleci2-multiple-node-versions/blob/npm/.circleci/config.yml

version: 2.1

commands:
  test-nodejs:
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: npm test

jobs:
  node-v8:
    docker:
      - image: node:8
    steps:
      - test-nodejs
  node-v10:
    docker:
      - image: node:10
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
